name: Rust wasm compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Perl environment
      # You may pin to the exact commit or the version.
      # uses: shogo82148/actions-setup-perl@04a9a397f834661fa6faf5aa6d16d14536249d2a
      uses: shogo82148/actions-setup-perl@v1.22.0
      with:
        perl-version: 5.32.1
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.7.0
      with:
        node-version: 18.15.0
      
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1.0.5
      with:
        rust-version: 1.69.0
      
    - run: npm --version
    
    - run: perl --version
    
    - run: rustup --version
      
    
